### ISSUE TITLE
Downloads in /media/usb-luca/Downloads ?

### ISSUE THREAD

**Issue by ssorgatem** [vexdev/amarr#59]
I get the following system message in lidarr and radarr:

"<div class="Table-tableContainer-QgrKY Table-horizontalScroll-pEqaG Scroller-scroller-lhubq Scroller-horizontal-Od7JK Scroller-autoScroll-RVZ6m" tabindex="-1" style="box-sizing: border-box; outline: none; scrollbar-color: var(--scrollbarBackgroundColor) transparent; scrollbar-width: thin; overflow: auto hidden; color: rgb(204, 204, 204); font-family: Roboto, &quot;open sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(32, 32, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
You are using docker; download client amule places downloads in /media/usb-luca/Downloads but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings. |  
-- | --

</div><br class="Apple-interchange-newline">"

However the path /media/usb-luca/Downloads is nowhere in my compose files or settings.

I have a folder, /external, mapped inside all my containers and have aMule downloading things to /external/media/Incoming, similar to how I have deluge set up for torrents

**Comment by vexdev** [comment]
Just released a fix, should go in 1.5.5.
If you still have issues please re-open.
