### ISSUE TITLE
Java exec format error when running amarr on portainer

### ISSUE THREAD

**Issue by miguesan01** [vexdev/amarr#74]
Amarr Apparently runs ok when I deploy the container in portainer, but soon after  exits with this error:

        exec /usr/local/openjdk-17/bin/java: exec format error

This is my configuration file:

---
version: "2.1"
services:
 amarr:
  image: vexdev/amarr:latest
  container_name: amarr
  environment:
    - AMULE_HOST=192.168.1.88
    - AMULE_PORT=4712
    - AMULE_PASSWORD=xxxxxx
    - AMULE_FINISHED_PATH=/finished
    - AMARR_LOG_LEVEL=INFO
  volumes:
    - /var/lib/docker/volumes/amarr:/config
    - /media/HDD/Media/downloads/complete:/finished
  ports:
    - 8080:8080
    
   Am I doing something wrong?
Thanks in advance.

**Comment by vexdev** [comment]
Should be fixed with version 1.6.0 released with arm support (#83 ) please re-open if not working.

**Comment by miguesan01** [comment]
I weren't aware that arm wasn't supported. Anyway, I moved to an i386 minipc and amarr is running ok, so I can't test it in arm anymore. Thank you.
