### ISSUE TITLE
 download client amarr places downloads in /finished

### ISSUE THREAD

**Issue by adocampo** [vexdev/amarr#85]
Hi there,

Finally, I got to configure the download client amarr in sonarr and radarr. But when the download finishes, sonarr doesn't import the download to the proper TV Show folder.

In the Activity tab, I can see this message
![image](https://github.com/vexdev/amarr/assets/2266612/4ba59a40-2d55-492b-957d-4f44c16cb1ff)

Which is also shown in the Sonarr and Radarr's health section.

> You are using docker; download client amarr places downloads in /finished but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.

I don't know where this `/finished` path is set, my guess is hardcoded into the amarr's docker, I've took a look into `config/` directory, but there are just two files, `categories.tsv` and  `hashes.tsv`

Entering the running docker instance, I cannot see either the `/finished` directory.

My amule docker instance has this volumes mapped
```yaml
    volumes:
      - '/data/.docker/amule/config:/home/amule/.aMule'
      - '/data/files/Downloads:/incoming'
      - '/data/files/Downloads/incomplete:/temp'
```
And when the file, downloaded with amule, via amarr/sonarr, is downloaded in my hosts' `/data/files/Downloads` or in my amule's `/incoming`...

As per this error, I can't even manually import the file
![image](https://github.com/vexdev/amarr/assets/2266612/8ea47a04-4c6c-4af0-a862-e11d04eb20ee)

Any idea what could I do?

**Comment by adocampo** [comment]
I've solved it by adding a new remote path mapping in Settings --> Download clients
![image](https://github.com/vexdev/amarr/assets/2266612/d417152a-ffb3-4db9-bb31-8a41bd0de753)

**Comment by vexdev** [comment]
Great! Another approach is to use the environment variable `AMULE_FINISHED_PATH` with amarr.

Example:

```
services:
  amarr:
    // ... omissis ...
    environment:
      - AMULE_FINISHED_PATH=/media/usb-luca/Adunanza/finished
```

**Comment by adocampo** [comment]
I didn't remember that environment from the README... 🤦🏻
