### ISSUE TITLE
Configuring amarr as a download client in radarr

### ISSUE THREAD

**Issue by tdam2112** [vexdev/amarr#90]
I'm a bit of a noob when it comes to these setups, so let me know if something doesn't make sense.
I have amule, radarr and amarr running on docker (amule and amarr are under a gluetun vpn host_network)
I followed the README instructions for the radarr setup:
- Name: amarr
- Host: (used the hostname of my container (echo $HOSTNAME on docker exec), amarr by itself was not connecting)
- Port: 8080
- Client Priority: 50

When I test the connection I get the following error on radarr:
`Failed to get the list of torrents: Failed to connect to qBittorrent, check your settings.`

Here are my amarr logs: [amarr_logs.pdf](https://github.com/user-attachments/files/16277393/amarr_logs.pdf)
Note: I tried testing 4 times, that's why the following pattern happens multiple times:
```
INFO  ktor.application - Getting download queue...
INFO  ktor.application - Reconnecting...
INFO  ktor.application - Authenticating...
```
however the error only shows up at the last attempt.
here are the amule logs [amule_logs.pdf](https://github.com/user-attachments/files/16277511/amule_logs.pdf), however, amule doesn't seem to respond to the radarr download client test.

**Comment by vexdev** [comment]
It looks like you have connectivity problems between amarr and amule, as well as between amarr and radarr. How do you configure your docker? Are you using docker compose?
Please share your configuration.

**Comment by tdam2112** [comment]
That might be it, I'm using gluetun https://github.com/qdm12/gluetun as a vpn client, not sure if that affects it
here is my docker compose: [compose.pdf](https://github.com/user-attachments/files/16284723/compose.pdf)
I've been using everything but amarr and amule for a long time, I'm trying to se these up at the same time however.

**Comment by vexdev** [comment]
As you're using `network_mode: "service:gluetun"` for both amarr and amule, both these services will share the same network. This means that from the perspective of amarr, the host of amule will simply be `localhost`, and that from the perspective of radarr, you need to connect through the port you are exposing from `gluetun`.

Two changes:
1. in the docker-compose, change the host of amule to localhost:
```
amarr:
 image: vexdev/amarr:latest
 container_name: amarr
 network_mode: "service:gluetun"
 environment:
 - AMULE_HOST=localhost
```
2. configure radarr to connect to the host `gluetun` port `8080`. (or for the indexer the following url: `http://gluetun:8080/indexer/amule`)

This should improve things.

**Comment by vexdev** [comment]
Also a note, there's no need to run amarr in a vpn as there's no traffic generated by amarr to external services, but it should work either way.

**Comment by tdam2112** [comment]
Hey, I found the problem, I switched AMULE-PORT to 4712 and it showed my AMULE_PASSWORD was wrong, turns out I had different passwords for the web UI and the service. Changing those fixed it for me.

**Comment by vexdev** [comment]
Great! Enjoy it
